version: '3.3'
services:
  eureka-discovery-service:
    image: eureka-discovery-service:0.0.1-SNAPSHOT
    container_name: eureka-discovery-service
    ports: 
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  mysql: 
    image: mysql:latest
    container_name: kwetter_account_db
    environment:
      MYSQL_ROOT_PASSWORD: Kw3tter!
      MYSQL_DATABASE: account_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Kw3tter!Pwd
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8060:80"
    restart: always
        
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Kw3tter!

  mongodb_tweet:
    image: mongo:latest
    container_name: mongodb_tweet
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Kw3tter!
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_tweet_container:/data/db
    ports:
      - "27017:27017"

  mongodb_timeline:
    image: mongo:latest
    container_name: mongodb_timeline
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Kw3tter!
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_timeline_container:/data/db
    ports:
      - "27018:27017"

  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  account-service:
    image: account-service:0.0.1-SNAPSHOT
    hostname: account-service
    restart: always
    ports:
      - "8069:8069"

    depends_on: 
      - mysql
      - eureka-discovery-service
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Kw3tter!
      SPRING_DATASOURCE_URL: jdbc:mysql://kwetter_account_db:3306/account_db?createDatabaseIfNotExist=true

  tweet-service:
    image: tweet-service:0.0.1-SNAPSHOT 
    hostname: tweet-service
    restart: always
    ports:
      - "8070:8070"

    depends_on: 
      - mongodb_tweet
      - eureka-discovery-service
    environment: 
      SPRING_DATA_MONGODB_HOST: mongodb_tweet
  
  api-gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    hostname: api-gateway
    restart: always
    ports:
      - "8050:8050"
    depends_on: 
      - tweet-service
      - account-service
      - eureka-discovery-service
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://tweet-service:8070
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: tweet-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/api/tweets/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://account-service:8069
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: account-service
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/api/account/**
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
volumes:
  mongodb_tweet_container:
  mongodb_timeline_container: