# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure for Students(5c35364a-836c-420f-8218-3ee41a64dfab)'
    azureResourceGroup: 'S6_kwetter-cluster-rg'
    kubernetesCluster: 'kwetter-cluster-v2'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'kubernetes/deployment.yml'
